sequenceDiagram
    participant M as Main
    participant U as User
    participant C as CashFlow
    participant W as Workflow
    participant A as Allocation
    participant P as Payment
    M->>U: create user
    U->>M: return user
    M->>C: create cashflow
    C->>M: return cashflow
    M->>W: create workflow
    W->>M: return workflow
    M->>A: create allocation
    A->>M: return allocation
    M->>P: create payment
    P->>M: return payment
